version: '3.1'

services:

  www-landonmanning-com:
    image: ghost:5-alpine
    restart: always
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      database__client: sqlite3
      database__connection__filename: "content/data/ghost.db"
      url: https://landonmanning.com

    # Development
    #   url: http://localhost:2808
    #   NODE_ENV: development
    # ports:
    #   - 2808:2368

networks:
  default:
    name: npm-net
    external: true
