version: '3.1'

services:

  www-landonmanning-com:
    image: ghost:5-alpine
    restart: always
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      database__client: sqlite3
      database__connection__filename: "content/data/ghost.db"
      url: https://landonmanning.com

      # url: http://localhost:2368
      # NODE_ENV: development

networks:
  default:
    name: npm-net
    external: true
